update yaml

diff --git a/.github/workflows/average-metrics.yaml b/.github/workflows/average-metrics.yaml
--- a/.github/workflows/average-metrics.yaml
+++ b/.github/workflows/average-metrics.yaml
@@ -11,8 +11,18 @@ jobs:
 
       - name: Post Request
         run:
-          curl -X POST \ https://app.netlify.com/sites/brain-exercise-initiative-analytics/deploys/6513b839abba8f0009d15c14/api/patient/internal/average-stats
-          -f body=' '
+          SECRET=$INTERNAL_AVGERAGE_SECRET
+
+          RESPONSE=$(curl -X POST -d "secret=$SECRET" https://app.netlify.com/sites/brain-exercise-initiative-analytics/deploys/6513b839abba8f0009d15c14/api/patient/internal/average-stats
+          
+          if [[ $RESPONSE == *"success = true"* ]]; then
+            echo "POST request was successful."
+          else
+            echo "POST request failed."
+            exit 1 # Set a non-zero exit code to indicate failure
+          fi
+
+
         env:
-          secret: ${{ secrets.INTERNAL_AVERAGE_SECRET }}
+          INTERNAL_AVGERAGE_SECRET: ${{ secrets.INTERNAL_AVERAGE_SECRET }}
 
